name: Update GitHub Stats

on:
  schedule:
    - cron: '0 */8 * * *' # Berjalan otomatis setiap hari jam 00:00 UTC
  workflow_dispatch: {} # Memungkinkan tombol run manual di tab Actions
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Diperlukan agar action bisa melakukan commit otomatis ke repo
      issues: read # Diperlukan agar action bisa membaca jumlah issue

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: python update_stats.py

      - name: Commit and push changes if any
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update real GitHub stats & badges"
          file_pattern: stats.json README.md